Not in virtualenv
cuDNN not found!
bazel not found
{'label': 'library', 'name': 'numpy', 'version': '1.8.1', 'verdict': 'no', 'post_id': ['45703036']}
{'label': 'library', 'name': 'numpy', 'version': '1.13.1', 'verdict': 'no', 'post_id': ['45703036']}
unknown
unknown
unknown
unknown
unknown
{'label': 'programming_language', 'name': 'python', 'version': '3.6', 'verdict': 'yes', 'post_id': ['59269352']}
{'label': 'programming_language', 'name': 'python', 'version': '3.5.6', 'verdict': 'yes', 'post_id': ['59269352']}
{'label': 'library', 'name': 'numpy', 'version': '6', 'verdict': 'yes', 'post_id': ['50201186']}
{'label': 'library', 'name': 'numpy', 'version': '1.14.3', 'verdict': 'yes', 'post_id': ['50201186']}
{'label': 'library', 'name': 'numpy', 'version': '1.15', 'verdict': 'yes', 'post_id': ['50201186', '51909734']}
{'label': 'library', 'name': 'numpy', 'version': '1.11.3', 'verdict': 'yes', 'post_id': ['45082155']}
......................................................................................
Current library: scipy (v1.1.0)
Knowledge base: {'library': {'numpy': [('1.8.1', 'no', ['45703036']), ('1.13.1', 'no', ['45703036']), ('6', 'yes', ['50201186']), ('1.14.3', 'yes', ['50201186']), ('1.15', 'yes', ['50201186', '51909734']), ('1.11.3', 'yes', ['45082155'])]}, 'hardware': {}, 'programming_language': {'python': [('3.6', 'yes', ['59269352']), ('3.5.6', 'yes', ['59269352'])]}, 'operating_system': {}, 'tool': {}, 'database': {}, 'software': {}}
{'label': 'programming_language', 'name': 'python', 'version': '3', 'verdict': 'yes', 'post_id': ['54617862']}
unknown
{'label': 'library', 'name': 'scipy', 'version': '1.2', 'verdict': 'yes', 'post_id': ['51909734', '52817582']}
{'label': 'library', 'name': 'scipy', 'version': '1.1', 'verdict': 'yes', 'post_id': ['50201186', '51909734']}
{'label': 'programming_language', 'name': 'python', 'version': '3.7.1', 'verdict': 'yes', 'post_id': ['53499006']}
......................................................................................
Current library: numpy (v1.15.4)
Knowledge base: {'library': {'scipy': [('1.2', 'yes', ['51909734', '52817582']), ('1.1', 'yes', ['50201186', '51909734'])]}, 'hardware': {}, 'programming_language': {'python': [('3', 'yes', ['54617862']), ('3.7.1', 'yes', ['53499006'])]}, 'operating_system': {}, 'tool': {}, 'database': {}, 'software': {}}
unknown
unknown
{'label': 'operating_system', 'name': 'ubuntu', 'version': '16.0.4', 'verdict': 'yes', 'post_id': ['59108370']}
unknown
unknown
{'label': 'library', 'name': 'tfds', 'version': '4', 'verdict': 'no', 'post_id': ['65795196']}
{'label': 'hardware', 'name': 'cuda', 'version': '11', 'verdict': 'no', 'post_id': ['65619544']}
{'label': 'hardware', 'name': 'cuda', 'version': '10.1', 'verdict': 'no', 'post_id': ['65432123']}
unknown
......................................................................................
Current library: tensorflow (v1.15.4)
Knowledge base: {'library': {'tfds': [('4', 'no', ['65795196'])]}, 'hardware': {'cuda': [('11', 'no', ['65619544']), ('10.1', 'no', ['65432123'])]}, 'programming_language': {}, 'operating_system': {'ubuntu': [('16.0.4', 'yes', ['59108370'])]}, 'tool': {}, 'database': {}, 'software': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local tensorflow (v1.15.4) is not compatible with cuda (v11.7) (0)
-----------------------------------END-------------------------------------------
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local tensorflow (v1.15.4) may not be compatible with ubuntu (v18.04) (1)
Recommend StackOverflow Posts: 
https://stackoverflow.com/questions/59108370
-----------------------------------END-------------------------------------------
