Not in virtualenv
cuDNN not found!
bazel not found
{'label': 'programming_language', 'name': 'python', 'version': '2', 'verdict': 'no', 'post_id': ['57734033']}
{'label': 'library', 'name': 'scipy', 'version': '1.0.1', 'verdict': 'no', 'post_id': ['57734033']}
{'label': 'programming_language', 'name': 'python', 'version': '3', 'verdict': 'yes', 'post_id': ['57734033']}
{'label': 'library', 'name': 'pandas', 'version': '0.22', 'verdict': 'yes', 'post_id': ['49677606']}
{'label': 'library', 'name': 'scipy', 'version': '1.1', 'verdict': 'yes', 'post_id': ['50201186']}
unknown
unknown
unknown
......................................................................................
Current library: numpy (v1.14.2)
Knowledge base: {'library': {'scipy': [('1.0.1', 'no', ['57734033']), ('1.1', 'yes', ['50201186'])], 'pandas': [('0.22', 'yes', ['49677606'])]}, 'hardware': {}, 'programming_language': {'python': [('2', 'no', ['57734033']), ('3', 'yes', ['57734033'])]}, 'operating_system': {}, 'tool': {}, 'database': {}, 'software': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local numpy (v1.14.2) may not be compatible with pandas (v1.3.5) (1)
Recommend StackOverflow Posts: 
https://stackoverflow.com/questions/49677606
-----------------------------------END-------------------------------------------
{'label': 'programming_language', 'name': 'python', 'version': '3', 'verdict': 'yes', 'post_id': ['57734033']}
{'label': 'library', 'name': 'numpy', 'version': '1.14.6', 'verdict': 'no', 'post_id': ['57734033']}
......................................................................................
Current library: scipy (v1.0.1)
Knowledge base: {'library': {'numpy': [('1.14.6', 'no', ['57734033'])]}, 'hardware': {}, 'programming_language': {'python': [('3', 'yes', ['57734033'])]}, 'operating_system': {}, 'tool': {}, 'database': {}, 'software': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local scipy (v1.0.1) is compatible with python (v3.6) (1)
Recommend StackOverflow Posts: 
https://stackoverflow.com/questions/57734033
-----------------------------------END-------------------------------------------
{'label': 'tool', 'name': 'bazel', 'version': '0.5.1', 'verdict': 'no', 'post_id': ['50518061']}
{'label': 'tool', 'name': 'bazel', 'version': '0.13.1', 'verdict': 'yes', 'post_id': ['50518061']}
unknown
unknown
{'label': 'library', 'name': 'keras', 'version': '2.0.5', 'verdict': 'no', 'post_id': ['46670544']}
{'label': 'hardware', 'name': 'cuda', 'version': '8', 'verdict': 'yes', 'post_id': ['46940714', '46189616', '46778006', '47008832']}
{'label': 'programming_language', 'name': 'python', 'version': '3.5.2', 'verdict': 'yes', 'post_id': ['46940714']}
{'label': 'hardware', 'name': 'cudnn', 'version': '7', 'verdict': 'no', 'post_id': ['58382360']}
{'label': 'library', 'name': 'keras', 'version': '2.2.2', 'verdict': 'yes', 'post_id': ['59044705']}
......................................................................................
Current library: tensorflow (v1.3.0)
Knowledge base: {'library': {'keras': [('2.0.5', 'no', ['46670544']), ('2.2.2', 'yes', ['59044705'])]}, 'hardware': {'cuda': [('8', 'yes', ['46940714', '46189616', '46778006', '47008832'])], 'cudnn': [('7', 'no', ['58382360'])]}, 'programming_language': {'python': [('3.5.2', 'yes', ['46940714'])]}, 'operating_system': {}, 'tool': {'bazel': [('0.5.1', 'no', ['50518061']), ('0.13.1', 'yes', ['50518061'])]}, 'database': {}, 'software': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local tensorflow (v1.3.0) is not compatible with cuda (v11.7) (0)
-----------------------------------END-------------------------------------------
--------------------------------DC ISSUE-----------------------------------------
cudnn is not installed in local, the recommended version is []
-----------------------------------END-------------------------------------------
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local tensorflow (v1.3.0) may not be compatible with python (v3.6) (1)
Recommend StackOverflow Posts: 
https://stackoverflow.com/questions/46940714
-----------------------------------END-------------------------------------------
