Not in virtualenv
cuDNN not found!
bazel not found
{'label': 'programming_language', 'name': 'python', 'version': '3.8', 'verdict': 'yes', 'post_id': ['68917678']}
{'label': 'programming_language', 'name': 'python', 'version': '3.9', 'verdict': 'yes', 'post_id': ['68917678']}
......................................................................................
Current library: numpy (v1.21.6)
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('3.8', 'yes', ['68917678']), ('3.9', 'yes', ['68917678'])]}, 'operating_system': {}, 'tool': {}, 'database': {}, 'software': {}}
{'label': 'tool', 'name': 'bazel', 'version': '0.5.1', 'verdict': 'no', 'post_id': ['50518061']}
{'label': 'tool', 'name': 'bazel', 'version': '0.13.1', 'verdict': 'yes', 'post_id': ['50518061']}
unknown
unknown
{'label': 'library', 'name': 'keras', 'version': '2.0.5', 'verdict': 'no', 'post_id': ['46670544']}
{'label': 'hardware', 'name': 'cuda', 'version': '8', 'verdict': 'yes', 'post_id': ['46940714', '46189616', '46778006', '47008832']}
{'label': 'programming_language', 'name': 'python', 'version': '3.5.2', 'verdict': 'yes', 'post_id': ['46940714']}
{'label': 'hardware', 'name': 'cudnn', 'version': '7', 'verdict': 'no', 'post_id': ['58382360']}
......................................................................................
Current library: tensorflow (v1.3)
Knowledge base: {'library': {'keras': [('2.0.5', 'no', ['46670544'])]}, 'hardware': {'cuda': [('8', 'yes', ['46940714', '46189616', '46778006', '47008832'])], 'cudnn': [('7', 'no', ['58382360'])]}, 'programming_language': {'python': [('3.5.2', 'yes', ['46940714'])]}, 'operating_system': {}, 'tool': {'bazel': [('0.5.1', 'no', ['50518061']), ('0.13.1', 'yes', ['50518061'])]}, 'database': {}, 'software': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local tensorflow (v1.3) is not compatible with cuda (v11.7) (0)
-----------------------------------END-------------------------------------------
--------------------------------DC ISSUE-----------------------------------------
cudnn is not installed in local, the recommended version is []
-----------------------------------END-------------------------------------------
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local tensorflow (v1.3) may not be compatible with python (v3.6) (1)
Recommend StackOverflow Posts: 
https://stackoverflow.com/questions/46940714
-----------------------------------END-------------------------------------------
