/data/home/zzk/workspace/zzk/Benchmark/projects/gcn/setup.py
/data/home/zzk/workspace/zzk/Benchmark/projects/gcn/gcn/inits.py
/data/home/zzk/workspace/zzk/Benchmark/projects/gcn/gcn/__init__.py
/data/home/zzk/workspace/zzk/Benchmark/projects/gcn/gcn/metrics.py
/data/home/zzk/workspace/zzk/Benchmark/projects/gcn/gcn/train.py
/data/home/zzk/workspace/zzk/Benchmark/projects/gcn/gcn/models.py
/data/home/zzk/workspace/zzk/Benchmark/projects/gcn/gcn/utils.py
/data/home/zzk/workspace/zzk/Benchmark/projects/gcn/gcn/layers.py
Not in virtualenv
cuDNN not found!
bazel not found
......................................................................................
Current library: scipy (v1.1.0)
Knowledge base: {'library': {'numpy': [('1.8.1rc1', 'no', ['45703036'])]}, 'hardware': {}, 'programming_language': {'python': [('3.6', 'no', ['59269352']), ('3.5.6', 'yes', ['59269352'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local scipy (v1.1.0) is not compatible with python (v3.6) (3)
Recommand StackOverflow Posts: 
https://stackoverflow.com/questions/59269352
-----------------------------------END-------------------------------------------
......................................................................................
Current library: numpy (v1.15.4)
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('3.7.1', 'yes', ['53499006'])]}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current library: tensorflow (v1.15.4)
Knowledge base: {'library': {'tfds': [('2.1', 'yes', ['68263473']), ('3.2.1', 'yes', ['65795196']), ('4', 'no', ['65795196'])], 'keras': [('2.3.1', 'yes', ['67171045'])]}, 'hardware': {'cuda': [('110', 'yes', ['65619544']), ('10', 'yes', ['59982494', '67734574', '60077642'])]}, 'programming_language': {'python': [('3.7', 'yes', ['61594971']), ('3.8', 'no', ['61594971'])]}, 'operating_system': {'ubuntu': [('16.0.4', 'yes', ['59108370'])]}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local tensorflow (v1.15.4) is not compatible with cuda (v11.2) (0)
-----------------------------------END-------------------------------------------
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local tensorflow (v1.15.4) may not be compatible with ubuntu (v18.04.1) (1)
Recommand StackOverflow Posts: 
https://stackoverflow.com/questions/59108370
-----------------------------------END-------------------------------------------
