/data/home/zzk/workspace/zzk/Benchmark/projects/polyrnn-pp/src/PolygonModel.py
/data/home/zzk/workspace/zzk/Benchmark/projects/polyrnn-pp/src/vis_predictions.py
/data/home/zzk/workspace/zzk/Benchmark/projects/polyrnn-pp/src/__init__.py
/data/home/zzk/workspace/zzk/Benchmark/projects/polyrnn-pp/src/inference.py
/data/home/zzk/workspace/zzk/Benchmark/projects/polyrnn-pp/src/poly_utils.py
/data/home/zzk/workspace/zzk/Benchmark/projects/polyrnn-pp/src/EvalNet.py
/data/home/zzk/workspace/zzk/Benchmark/projects/polyrnn-pp/src/GGNNPolyModel.py
/data/home/zzk/workspace/zzk/Benchmark/projects/polyrnn-pp/src/utils.py
Not in virtualenv
cuDNN not found!
bazel not found
......................................................................................
Current library: numpy (v1.14.2)
Knowledge base: {'library': {'keras': [('2.2.4', 'yes', ['53617072'])]}, 'hardware': {}, 'programming_language': {'python': [('3', 'yes', ['57734033'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local numpy (v1.14.2) may not be compatible with python (v3.6) (1)
Recommand StackOverflow Posts: 
https://stackoverflow.com/questions/57734033
-----------------------------------END-------------------------------------------
......................................................................................
Current library: scipy (v1.0.1)
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('3', 'yes', ['57734033'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local scipy (v1.0.1) may not be compatible with python (v3.6) (1)
Recommand StackOverflow Posts: 
https://stackoverflow.com/questions/57734033
-----------------------------------END-------------------------------------------
......................................................................................
Current library: tensorflow (v1.3.0)
Knowledge base: {'library': {}, 'hardware': {'cudnn': [('64', 'yes', ['43566341', '46080926', '45779371']), ('7', 'no', ['58382360'])], 'cuda': [('9', 'no', ['46689778', '58382360', '47008832']), ('8', 'yes', ['46189616', '46778006', '46940714', '47008832'])]}, 'programming_language': {}, 'operating_system': {}, 'tool': {'bazel': [('0.13.1', 'yes', ['50518061']), ('0.5.1', 'yes', ['50518061'])]}}
--------------------------------DC ISSUE-----------------------------------------
cudnn is not installed in local, the recommended version is ['64']
-----------------------------------END-------------------------------------------
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local tensorflow (v1.3.0) is not compatible with cuda (v11.2) (0)
-----------------------------------END-------------------------------------------
