Not in virtualenv
cuDNN not found!
bazel not found
unknown
......................................................................................
Current library: scipy (v0.18.1)
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}, 'database': {}, 'software': {}}
{'label': 'programming_language', 'name': 'python', 'version': '3.5', 'verdict': 'yes', 'post_id': ['25535723']}
{'label': 'programming_language', 'name': 'python', 'version': '3.5', 'verdict': 'yes', 'post_id': ['67923439']}
{'label': 'programming_language', 'name': 'python', 'version': '3.6', 'verdict': 'no', 'post_id': ['67923439']}
{'label': 'library', 'name': 'pandas', 'version': '0.18.1', 'verdict': 'no', 'post_id': ['67923439']}
{'label': 'library', 'name': 'scipy', 'version': '1.11.3', 'verdict': 'yes', 'post_id': ['45082155']}
......................................................................................
Current library: numpy (v1.11.1)
Knowledge base: {'library': {'pandas': [('0.18.1', 'no', ['67923439'])], 'scipy': [('1.11.3', 'yes', ['45082155'])]}, 'hardware': {}, 'programming_language': {'python': [('3.5', 'yes', ['25535723']), ('3.5', 'yes', ['67923439']), ('3.6', 'no', ['67923439'])]}, 'operating_system': {}, 'tool': {}, 'database': {}, 'software': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local numpy (v1.11.1) is not compatible with python (v3.6) (3)
Recommend StackOverflow Posts: 
https://stackoverflow.com/questions/67923439
-----------------------------------END-------------------------------------------
{'label': 'tool', 'name': 'bazel', 'version': '0.5.1', 'verdict': 'no', 'post_id': ['50518061']}
{'label': 'tool', 'name': 'bazel', 'version': '0.13.1', 'verdict': 'yes', 'post_id': ['50518061']}
unknown
unknown
{'label': 'library', 'name': 'keras', 'version': '2.0.5', 'verdict': 'no', 'post_id': ['46670544']}
{'label': 'hardware', 'name': 'cuda', 'version': '8', 'verdict': 'yes', 'post_id': ['46940714', '46189616', '46778006', '47008832']}
{'label': 'programming_language', 'name': 'python', 'version': '3.5.2', 'verdict': 'yes', 'post_id': ['46940714']}
{'label': 'hardware', 'name': 'cudnn', 'version': '7', 'verdict': 'no', 'post_id': ['58382360']}
{'label': 'library', 'name': 'keras', 'version': '2.2.2', 'verdict': 'yes', 'post_id': ['59044705']}
......................................................................................
Current library: tensorflow (v1.3.0)
Knowledge base: {'library': {'keras': [('2.0.5', 'no', ['46670544']), ('2.2.2', 'yes', ['59044705'])]}, 'hardware': {'cuda': [('8', 'yes', ['46940714', '46189616', '46778006', '47008832'])], 'cudnn': [('7', 'no', ['58382360'])]}, 'programming_language': {'python': [('3.5.2', 'yes', ['46940714'])]}, 'operating_system': {}, 'tool': {'bazel': [('0.5.1', 'no', ['50518061']), ('0.13.1', 'yes', ['50518061'])]}, 'database': {}, 'software': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local tensorflow (v1.3.0) is not compatible with cuda (v11.7) (0)
-----------------------------------END-------------------------------------------
--------------------------------DC ISSUE-----------------------------------------
cudnn is not installed in local, the recommended version is []
-----------------------------------END-------------------------------------------
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local tensorflow (v1.3.0) may not be compatible with python (v3.6) (1)
Recommend StackOverflow Posts: 
https://stackoverflow.com/questions/46940714
-----------------------------------END-------------------------------------------
