/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/config_mri.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/config.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/util.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/dataset_tool_mri.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/dataset_tool_tf.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/dataset.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/train.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/validation.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/train_mri.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/network.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/download_kodak.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/dnnlib/util.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/dnnlib/__init__.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/dnnlib/submission/__init__.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/dnnlib/submission/submit.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/dnnlib/submission/run_context.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/dnnlib/submission/_internal/run.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/dnnlib/tflib/autosummary.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/dnnlib/tflib/__init__.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/dnnlib/tflib/network.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/dnnlib/tflib/optimizer.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/dnnlib/tflib/tfutil.py
Not in virtualenv
cuDNN not found!
bazel not found
......................................................................................
Current library: scipy (v1.1.0)
Knowledge base: {'library': {'numpy': [('1.8.1rc1', 'no', ['45703036'])]}, 'hardware': {}, 'programming_language': {'python': [('3.6', 'no', ['59269352']), ('3.5.6', 'yes', ['59269352'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local scipy (v1.1.0) may not be compatible with python (v3.6) (4)
Recommand StackOverflow Posts: 
https://stackoverflow.com/questions/59269352
-----------------------------------END-------------------------------------------
tensorflow is not installed in local
++++++++++++++++++++++++++++API CHECK++++++++++++++++++++++++++++
......................................................................................
Current API: session.run
Knowledge base: {'library': {'tensorflow': [('r0.10', 'yes', ['39787108'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: pickle.dump
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('2', 'yes', ['31915492']), ('3', 'yes', ['31915492'])]}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: tf.data
Knowledge base: {'library': {'tensorflow': [('1.5', 'yes', ['46732695'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: importlib.import_module
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('3', 'yes', ['301146'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: importlib.import_module may not be compatible with python (v3.6) (1)
Recommand StackOverflow Posts: 
https://stackoverflow.com/questions/301146
-----------------------------------END-------------------------------------------
......................................................................................
Current API: tf.nn.conv2d
Knowledge base: {'library': {}, 'hardware': {'cudnn': [('6', 'yes', ['47354833'])]}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: np.sum
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('4.5ms', 'yes', ['66886682'])]}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: np.float32
Knowledge base: {'library': {'numpy': [('1.6', 'yes', ['5876823'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: tf.random_normal
Knowledge base: {'library': {'tensorflow': [('1', 'no', ['65740996'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: np.cos
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('3', 'no', ['44480533'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local np.cos is not compatible with python (v3.6) (2)
Recommand StackOverflow Posts: 
https://stackoverflow.com/questions/44480533
-----------------------------------END-------------------------------------------
......................................................................................
Current API: tf.nn.max_pool
Knowledge base: {'library': {}, 'hardware': {'cudnn': [('6', 'yes', ['47354833'])]}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: tf.contrib
Knowledge base: {'library': {'tensorflow': [('0.12.1', 'yes', ['41638676']), ('1', 'no', ['59130063', '55872941', '61628580', '58607239']), ('2', 'no', ['59130063', '62580933', '53534547', '54360818', '55524156', '55872941', '55911034', '57629649', '59816366', '61628580', '54342829', '58607239', '68784711'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: tf.clip_by_value
Knowledge base: {'library': {'tensorflow': [('1.4', 'yes', ['50026224'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: os.listdir
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('3', 'yes', ['44661513', '48393588']), ('3.5', 'yes', ['44661513', '48393588']), ('10.6', 'yes', ['15236292']), ('2', 'yes', ['35375779', '63855912', '41447012', '48393588'])]}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: collections.defaultdict
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('2.5', 'yes', ['224876', '473108', '636125', '2728353', '3199196', '3784101', '4929456', '6770489'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: collections.defaultdict may not be compatible with python (v3.6) (1)
Recommand StackOverflow Posts: 
https://stackoverflow.com/questions/224876
https://stackoverflow.com/questions/473108
https://stackoverflow.com/questions/636125
https://stackoverflow.com/questions/2728353
https://stackoverflow.com/questions/3199196
https://stackoverflow.com/questions/3784101
https://stackoverflow.com/questions/4929456
https://stackoverflow.com/questions/6770489
-----------------------------------END-------------------------------------------
......................................................................................
Current API: tf.device
Knowledge base: {'library': {'tensorflow': [('3', 'yes', ['45544750'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: os.walk
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('4.10', 'yes', ['48393588']), ('3.5', 'no', ['44661513']), ('3.1', 'no', ['2485843']), ('2', 'yes', ['35375779', '1052293']), ('3.2', 'no', ['20585550'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local os.walk may not be compatible with python (v3.6) (4)
-----------------------------------END-------------------------------------------
......................................................................................
Current API: os.makedirs
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('3.5', 'no', ['48987444'])]}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: pickle.load
Knowledge base: {'library': {'numpy': [('3.7.2', 'yes', ['54777655'])]}, 'hardware': {}, 'programming_language': {'python': [('3', 'yes', ['54777655']), ('2', 'yes', ['54777655', '37394571']), ('3.3', 'yes', ['22863259'])]}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: self.name
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('3.6', 'yes', ['57533907'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: self.name may not be compatible with python (v3.6) (1)
Recommand StackOverflow Posts: 
https://stackoverflow.com/questions/57533907
-----------------------------------END-------------------------------------------
......................................................................................
Current API: inspect.getsource
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('3.6', 'yes', ['427504'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: inspect.getsource may not be compatible with python (v3.6) (1)
Recommand StackOverflow Posts: 
https://stackoverflow.com/questions/427504
-----------------------------------END-------------------------------------------
......................................................................................
Current API: urllib.request
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('3', 'yes', ['37316735', '49807887', '22776', '419268', '1393367', '1731697', '2792652', '3302479', '3956026', '5538568', '7617738', '10161363', '26236748', '41338150', '45401068', '66234986'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: urllib.request may not be compatible with python (v3.6) (1)
Recommand StackOverflow Posts: 
https://stackoverflow.com/questions/37316735
https://stackoverflow.com/questions/49807887
https://stackoverflow.com/questions/22776
https://stackoverflow.com/questions/419268
https://stackoverflow.com/questions/1393367
https://stackoverflow.com/questions/1731697
https://stackoverflow.com/questions/2792652
https://stackoverflow.com/questions/3302479
https://stackoverflow.com/questions/3956026
https://stackoverflow.com/questions/5538568
https://stackoverflow.com/questions/7617738
https://stackoverflow.com/questions/10161363
https://stackoverflow.com/questions/26236748
https://stackoverflow.com/questions/41338150
https://stackoverflow.com/questions/45401068
https://stackoverflow.com/questions/66234986
-----------------------------------END-------------------------------------------
......................................................................................
Current API: tf.split
Knowledge base: {'library': {'tensorflow': [('0.12', 'yes', ['41862548'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: np.array
Knowledge base: {'library': {'numpy': [('0.325', 'yes', ['67695754']), ('8.99849401', 'yes', ['46085625']), ('21.87729639', 'yes', ['46085625'])]}, 'hardware': {}, 'programming_language': {'python': [('3', 'no', ['3877247'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local np.array is not compatible with python (v3.6) (2)
Recommand StackOverflow Posts: 
https://stackoverflow.com/questions/3877247
-----------------------------------END-------------------------------------------
......................................................................................
Current API: glob.glob
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('3', 'yes', ['44661513', '48393588']), ('3.5', 'no', ['37173091', '44661513'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local glob.glob is not compatible with python (v3.6) (3)
-----------------------------------END-------------------------------------------
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local glob.glob may not be compatible with python (v3.6) (4)
-----------------------------------END-------------------------------------------
......................................................................................
Current API: shutil.copyfile
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('2', 'yes', ['24064783'])]}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: os.path.exists
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('3', 'yes', ['44661513']), ('2', 'no', ['44661513'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local os.path.exists is not compatible with python (v3.6) (3)
-----------------------------------END-------------------------------------------
......................................................................................
Current API: sys.exit
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('17.2.1', 'no', ['1603009']), ('0.10', 'no', ['1217465']), ('2', 'yes', ['1179060'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local sys.exit is not compatible with python (v3.6) (3)
-----------------------------------END-------------------------------------------
......................................................................................
Current API: urllib.request.urlretrieve
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('3.9.2', 'Unknown', ['']), ('3', 'yes', ['22776', '3042786', '4355529', '12100154'])]}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: os.path
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('3.5', 'yes', ['37095733']), ('2.7', 'yes', ['3430395']), ('3', 'yes', ['3430395', '4119176', '44661513']), ('3.4', 'no', ['45223014', '51149057'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local os.path is not compatible with python (v3.6) (3)
-----------------------------------END-------------------------------------------
......................................................................................
Current API: tf.zeros
Knowledge base: {'library': {'tensorflow': [('2', 'yes', ['59585408']), ('1.5', 'yes', ['59585408'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: os.path.join
Knowledge base: {'library': {'tensorflow': [('8', 'no', ['6766266'])]}, 'hardware': {}, 'programming_language': {'python': [('9', 'no', ['47748008']), ('3', 'no', ['6766266']), ('3.4', 'no', ['2909998'])]}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: np.dtype
Knowledge base: {'library': {'numpy': [('3.95', 'yes', ['44866614'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: os.path.isdir
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('3', 'yes', ['44661513'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: os.path.isdir may not be compatible with python (v3.6) (1)
Recommand StackOverflow Posts: 
https://stackoverflow.com/questions/44661513
-----------------------------------END-------------------------------------------
......................................................................................
Current API: tf.cond
Knowledge base: {'library': {'tensorflow': [('1', 'no', ['67691106']), ('1.4', 'yes', ['47769761'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: tf.shape
Knowledge base: {'library': {'tensorflow': [('1.8', 'yes', ['50414384']), ('r1.1', 'yes', ['43883326'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: tf.get_variable
Knowledge base: {'library': {'tensorflow': [('1.4', 'yes', ['47189751'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: tf.constant
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: re.compile
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('2.7', 'yes', ['30235809', '9914798'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: re.compile may not be compatible with python (v3.6) (1)
Recommand StackOverflow Posts: 
https://stackoverflow.com/questions/30235809
https://stackoverflow.com/questions/9914798
-----------------------------------END-------------------------------------------
......................................................................................
Current API: np.zeros
Knowledge base: {'library': {'numpy': [('3.95', 'yes', ['44866614'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: tf.placeholder
Knowledge base: {'library': {'tensorflow': [('2', 'no', ['60316058']), ('1.3', 'yes', ['47051723'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: tf.assign
Knowledge base: {'library': {'keras': [('2.1', 'yes', ['47081613'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: np.arange
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('3', 'yes', ['8097594']), ('2', 'yes', ['8097594']), ('6.65', 'yes', ['4618954'])]}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: tf.tile
Knowledge base: {'library': {'tensorflow': [('1.12', 'no', ['59577132'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
